= pre-commit-hooks

Reusable hook configurations for the https://pre-commit.com/[pre-commit] framework.

== Available hooks

`validate-commit-message`::
Validates that commit messages follow the format `<type>: <description>`, where `<type>` is one of the allowed revision types.

== Usage

Reference this repository in your project's `.pre-commit-config.yaml`:

[source,yaml]
----
default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/kieranpotts/pre-commit-hooks
    rev: <version>
    hooks:
      - id: validate-commit-message
----

Replace `<version>` with a tag or commit SHA from this repository.

You will need to install the https://pre-commit.com[pre-commit] framework on any system where you want to run pre-commit checks. You need only to run the following command once to install pre-commit system-wide:

[source,bash]
----
pip install pre-commit
----

Then install the pre-commit hooks in every local repository where you want pre-commit checks to be run. That includes this repository – it eats its own dog food, consuming the same hooks it shares with other repositories.

[source,bash]
----
pre-commit install
----

This installs all hook types declared in `.pre-commit-config.yaml` (`pre-commit`, `commit-msg`).

''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[MIT license]
